#!/usr/bin/env python3
"""
Demo script showing how to use the Forex Trading Bot.
This demonstrates the bot's capabilities without requiring API keys.
"""

print("=" * 70)
print("AI-Powered Forex Trading Bot - Demo")
print("=" * 70)
print()

print("This bot provides the following features:")
print()
print("📊 TRADING FEATURES:")
print("  • Automated forex trading via OANDA (practice account)")
print("  • Moving Average Crossover strategy (50/200 SMA)")
print("  • Risk management: 1% risk per trade")
print("  • Auto stop-loss (1%) and take-profit (2%)")
print()

print("🤖 AI INTEGRATION:")
print("  • OpenAI GPT portfolio analysis")
print("  • Real-time trading suggestions")
print("  • Risk assessment and diversification advice")
print("  • Interactive chat interface")
print()

print("📱 NOTIFICATIONS:")
print("  • Telegram alerts for all trades")
print("  • Entry/exit notifications with P&L")
print("  • AI insights delivered to your phone")
print("  • Daily performance summaries")
print()

print("💻 USER INTERFACE:")
print("  • Tkinter GUI for easy configuration")
print("  • Real-time dashboard with positions and P&L")
print("  • AI chat interface")
print("  • System logs viewer")
print()

print("📈 BACKTESTING:")
print("  • Test strategies on historical data")
print("  • Performance metrics (Sharpe ratio, drawdown, win rate)")
print("  • Backtrader integration")
print()

print("=" * 70)
print("SETUP INSTRUCTIONS:")
print("=" * 70)
print()

print("1. Install dependencies:")
print("   pip install -r requirements.txt")
print()

print("2. Get your API keys:")
print()
print("   OANDA (Free Practice Account):")
print("   → https://www.oanda.com/us-en/trading/demo-account/")
print()
print("   OpenAI API:")
print("   → https://platform.openai.com/api-keys")
print()
print("   Telegram Bot:")
print("   → Search for @BotFather on Telegram")
print()

print("3. Configure:")
print("   cp config_template.py config.py")
print("   # Edit config.py with your API keys")
print()

print("4. Run the bot:")
print("   python forex_bot.py")
print()

print("=" * 70)
print("FILE STRUCTURE:")
print("=" * 70)
print()
print("forex_bot.py          - Main bot controller")
print("broker_connector.py   - OANDA/CCXT integration")
print("forex_strategy.py     - Trading strategy logic")
print("ai_manager.py         - OpenAI GPT integration")
print("telegram_notifier.py  - Telegram notifications")
print("forex_gui.py          - Tkinter GUI interface")
print("backtester.py         - Backtesting framework")
print("config_template.py    - Configuration template")
print()

print("=" * 70)
print("STRATEGY DETAILS:")
print("=" * 70)
print()
print("Moving Average Crossover Strategy:")
print()
print("ENTRY SIGNALS:")
print("  • BUY:  50-SMA crosses above 200-SMA")
print("  • SELL: 50-SMA crosses below 200-SMA")
print()
print("EXIT CONDITIONS:")
print("  • Stop-loss hit (1% from entry)")
print("  • Take-profit hit (2% from entry)")
print("  • Reverse crossover signal")
print()
print("RISK MANAGEMENT:")
print("  • 1% maximum risk per trade")
print("  • Position sizing based on stop-loss distance")
print("  • Maximum drawdown monitoring (default 10%)")
print("  • No over-leveraging")
print()

print("=" * 70)
print("SUPPORTED FOREX PAIRS:")
print("=" * 70)
print()
print("Major Pairs:")
print("  • EUR/USD, GBP/USD, USD/JPY")
print("  • USD/CHF, AUD/USD, USD/CAD")
print("  • NZD/USD")
print()
print("Cross Pairs:")
print("  • EUR/GBP, EUR/JPY, GBP/JPY")
print("  • AUD/JPY, EUR/CHF, etc.")
print()
print("(Any pair supported by OANDA can be traded)")
print()

print("=" * 70)
print("SAFETY & DISCLAIMER:")
print("=" * 70)
print()
print("⚠️  IMPORTANT:")
print()
print("  • This bot is for EDUCATIONAL purposes only")
print("  • Always start with a PRACTICE account")
print("  • Never trade with money you can't afford to lose")
print("  • Past performance doesn't guarantee future results")
print("  • The AI provides suggestions, not financial advice")
print()
print("  OANDA practice accounts are FREE and safe for learning!")
print()

print("=" * 70)
print("Ready to start? Follow the setup instructions above!")
print("=" * 70)
print()
print("For questions or issues:")
print("  • Check README.md for detailed documentation")
print("  • Open an issue on GitHub")
print("  • Review the troubleshooting section")
print()
